Домашнее задание 3 - написание каркаса кода и тестов для БД
cpp-park-vk-education/2022_2_SVAG pull request #7
Opened 2022-11-21 14:28 UTC by vvinokurshin

2022-12-04 11:08 UTC, DPeshkoff requested changes
Привет! Посмотрел первую итерацию ревью.

Не проходит CI (-50%) - в остальном хорошая работа)

Предварительный балл 5/10, дедлайн по исправлениям 11.12.2022

2022-12-04 11:08 UTC, DPeshkoff commented on DoIt/tests/tests_database.cpp
> +    ASSERT_EQ(response["status"], "ok");
Кажется, что лучше expect

2022-12-04 22:15 UTC, vvinokurshin commented
Замечания исправлены

2022-12-12 17:40 UTC, DPeshkoff approved these changes
Привет! Посмотрел вторую итерацию.

10/10

2022-12-12 17:40 UTC, DPeshkoff commented on DoIt/CMakeLists.txt
> +# set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} "-lpqxx -lpq")
?

2023-01-05 00:26 UTC, merged